# Generated by Django 2.0.2 on 2018-04-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfg_app', '0004_auto_20180422_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
